INC=/usr/include


INCLIB=$(INC)/../lib

UNAME := $(shell uname)

CFLAGS= -I$(INC) -O3 -I.. -g

NAME= mlx-test
SRC = main.c
OBJ = $(SRC:%.c=%.o)

LFLAGS = -L.. -lmlx -L$(INCLIB) -lXext -lX11 -lm

ifeq ($(UNAME), Darwin)
	# mac
	CC = clang
else ifeq ($(UNAME), FreeBSD)
	# FreeBSD
	CC = clang
else
	#Linux and others...
	CC	= gcc
	LFLAGS += -lbsd
endif

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) -o $(NAME) $(OBJ) $(LFLAGS)

show:
	@ft_printf "UNAME		: $(UNAME)\n"
	@ft_printf "NAME  		: $(NAME)\n"
	@ft_printf "CC		: $(CC)\n"
	@ft_printf "CFLAGS		: $(CFLAGS)\n"
	@ft_printf "LFLAGS		: $(LFLAGS)\n"
	@ft_printf "SRC		:\n	$(SRC)\n"
	@ft_printf "OBJ		:\n	$(OBJ)\n"

clean:
	rm -f $(NAME) $(OBJ) *~ core *.core

re: clean all
